name: NPM-Publish

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on release branch
      - release

  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on release branch
      - release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.CLEAR_PLUGIN_NPM_TOKEN }}
