name: NPM-Publish

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on main branch
      - main

  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on main branch
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install pnpm -g && pnpm install
      - run: pnpm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
